### ISSUE TITLE
The "vendor-dir" parameter for "shared-package" configuration should be provided in your project composer.json ("extra" key)

### ISSUE THREAD

**Issue by nibsirahsieu** [Letudiant/composer-shared-package-plugin#5]
When running `composer install --prefer-dist` i always got the exception above.

here is my composer.json

```yml
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.7",
        "doctrine/dbal": "<2.5",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "propel/propel-bundle": "~1.4",
        "ircmaxell/password-compat": "~1.0",
        "whiteoctober/breadcrumbs-bundle": "~1.1",
        "league/csv": "^7.1@dev",
        "white-october/pagerfanta-bundle": "~1.0",
        "ramsey/array_column": "~1.1",
        "salva/jshrink-bundle": "~1.1",
        "hpatoio/deploy-bundle": "~1.5",
        "emiliomg/propel-provider-behavior-bundle": "@stable"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "letudiant/composer-shared-package-plugin": "~2.0"
    },
    "extra": {
        "shared-package": {
            "vendor-dir": "../php-shared-vendors/vendor",
            "package-list": [
                "symfony/symfony",
                "doctrine/dbal",
                "symfony/monolog-bundle",
                "sensio/distribution-bundle",
                "sensio/framework-extra-bundle",
                "incenteev/composer-parameter-handler",
                "propel/propel-bundle",
                "ircmaxell/password-compat",
                "whiteoctober/breadcrumbs-bundle",
                "ramsey/array_column",
                "salva/jshrink-bundle",
                "hpatoio/deploy-bundle"
            ]
        }
    }
```
is there something missing in my configuration?
